// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Sat Apr 20 15:58:58 2024

CU CU_inst
(
	.trig(trig_sig) ,	// input  trig_sig
	.Clk(Clk_sig) ,	// input  Clk_sig
	.ClrE(ClrE_sig) ,	// input  ClrE_sig
	.ClrA(ClrA_sig) ,	// input  ClrA_sig
	.value(value_sig) ,	// input [3:0] value_sig
	.Reset(Reset_sig) ,	// output  Reset_sig
	.LoadA(LoadA_sig) ,	// output  LoadA_sig
	.LoadB(LoadB_sig) ,	// output  LoadB_sig
	.AddSub(AddSub_sig) ,	// output  AddSub_sig
	.LoadR(LoadR_sig) ,	// output  LoadR_sig
	.IUAU(IUAU_sig) 	// output  IUAU_sig
);

defparam CU_inst.S0 = 'b000;
defparam CU_inst.S1 = 'b001;
defparam CU_inst.S2 = 'b010;
defparam CU_inst.S3 = 'b011;
defparam CU_inst.S4 = 'b100;
