// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Wed Apr 24 16:51:04 2024

IU IU_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.clear(clear_sig) ,	// input  clear_sig
	.Row(Row_sig) ,	// input [3:0] Row_sig
	.Col(Col_sig) ,	// output [3:0] Col_sig
	.LEDR(LEDR_sig) ,	// output [7:0] LEDR_sig
	.Val(Val_sig) ,	// output [3:0] Val_sig
	.LED(LED_sig) ,	// output  LED_sig
	.trig(trig_sig) 	// output  trig_sig
);

