// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Fri Apr 12 14:11:39 2024

keypad_input keypad_input_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.row(row_sig) ,	// input [3:0] row_sig
	.col(col_sig) ,	// output [3:0] col_sig
	.out(out_sig) ,	// output [DIGITS*4-1:0] out_sig
	.value(value_sig) ,	// output [3:0] value_sig
	.trig(trig_sig) 	// output  trig_sig
);

defparam keypad_input_inst.DIGITS = 4;
